# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vic/Documents/bparser

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vic/Documents/bparser

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vic/Documents/bparser/CMakeFiles /home/vic/Documents/bparser/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vic/Documents/bparser/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vtest_speed_sse

# Build rule for target.
vtest_speed_sse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vtest_speed_sse
.PHONY : vtest_speed_sse

# fast build rule for target.
vtest_speed_sse/fast:
	$(MAKE) -f CMakeFiles/vtest_speed_sse.dir/build.make CMakeFiles/vtest_speed_sse.dir/build
.PHONY : vtest_speed_sse/fast

#=============================================================================
# Target rules for targets named test_speed

# Build rule for target.
test_speed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_speed
.PHONY : test_speed

# fast build rule for target.
test_speed/fast:
	$(MAKE) -f CMakeFiles/test_speed.dir/build.make CMakeFiles/test_speed.dir/build
.PHONY : test_speed/fast

#=============================================================================
# Target rules for targets named test_speed_sse

# Build rule for target.
test_speed_sse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_speed_sse
.PHONY : test_speed_sse

# fast build rule for target.
test_speed_sse/fast:
	$(MAKE) -f CMakeFiles/test_speed_sse.dir/build.make CMakeFiles/test_speed_sse.dir/build
.PHONY : test_speed_sse/fast

#=============================================================================
# Target rules for targets named test_speed_bin

# Build rule for target.
test_speed_bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_speed_bin
.PHONY : test_speed_bin

# fast build rule for target.
test_speed_bin/fast:
	$(MAKE) -f CMakeFiles/test_speed_bin.dir/build.make CMakeFiles/test_speed_bin.dir/build
.PHONY : test_speed_bin/fast

#=============================================================================
# Target rules for targets named test_parser_bin

# Build rule for target.
test_parser_bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_parser_bin
.PHONY : test_parser_bin

# fast build rule for target.
test_parser_bin/fast:
	$(MAKE) -f CMakeFiles/test_parser_bin.dir/build.make CMakeFiles/test_parser_bin.dir/build
.PHONY : test_parser_bin/fast

#=============================================================================
# Target rules for targets named test_parser

# Build rule for target.
test_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_parser
.PHONY : test_parser

# fast build rule for target.
test_parser/fast:
	$(MAKE) -f CMakeFiles/test_parser.dir/build.make CMakeFiles/test_parser.dir/build
.PHONY : test_parser/fast

#=============================================================================
# Target rules for targets named vtest_array

# Build rule for target.
vtest_array: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vtest_array
.PHONY : vtest_array

# fast build rule for target.
vtest_array/fast:
	$(MAKE) -f CMakeFiles/vtest_array.dir/build.make CMakeFiles/vtest_array.dir/build
.PHONY : vtest_array/fast

#=============================================================================
# Target rules for targets named test_speed_sse_bin

# Build rule for target.
test_speed_sse_bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_speed_sse_bin
.PHONY : test_speed_sse_bin

# fast build rule for target.
test_speed_sse_bin/fast:
	$(MAKE) -f CMakeFiles/test_speed_sse_bin.dir/build.make CMakeFiles/test_speed_sse_bin.dir/build
.PHONY : test_speed_sse_bin/fast

#=============================================================================
# Target rules for targets named bparser

# Build rule for target.
bparser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bparser
.PHONY : bparser

# fast build rule for target.
bparser/fast:
	$(MAKE) -f CMakeFiles/bparser.dir/build.make CMakeFiles/bparser.dir/build
.PHONY : bparser/fast

#=============================================================================
# Target rules for targets named vtest_parser

# Build rule for target.
vtest_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vtest_parser
.PHONY : vtest_parser

# fast build rule for target.
vtest_parser/fast:
	$(MAKE) -f CMakeFiles/vtest_parser.dir/build.make CMakeFiles/vtest_parser.dir/build
.PHONY : vtest_parser/fast

#=============================================================================
# Target rules for targets named test_processor_bin

# Build rule for target.
test_processor_bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_processor_bin
.PHONY : test_processor_bin

# fast build rule for target.
test_processor_bin/fast:
	$(MAKE) -f CMakeFiles/test_processor_bin.dir/build.make CMakeFiles/test_processor_bin.dir/build
.PHONY : test_processor_bin/fast

#=============================================================================
# Target rules for targets named test_array_bin

# Build rule for target.
test_array_bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_array_bin
.PHONY : test_array_bin

# fast build rule for target.
test_array_bin/fast:
	$(MAKE) -f CMakeFiles/test_array_bin.dir/build.make CMakeFiles/test_array_bin.dir/build
.PHONY : test_array_bin/fast

#=============================================================================
# Target rules for targets named vtest_speed

# Build rule for target.
vtest_speed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vtest_speed
.PHONY : vtest_speed

# fast build rule for target.
vtest_speed/fast:
	$(MAKE) -f CMakeFiles/vtest_speed.dir/build.make CMakeFiles/vtest_speed.dir/build
.PHONY : vtest_speed/fast

#=============================================================================
# Target rules for targets named test_array

# Build rule for target.
test_array: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_array
.PHONY : test_array

# fast build rule for target.
test_array/fast:
	$(MAKE) -f CMakeFiles/test_array.dir/build.make CMakeFiles/test_array.dir/build
.PHONY : test_array/fast

#=============================================================================
# Target rules for targets named test_grammar

# Build rule for target.
test_grammar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_grammar
.PHONY : test_grammar

# fast build rule for target.
test_grammar/fast:
	$(MAKE) -f CMakeFiles/test_grammar.dir/build.make CMakeFiles/test_grammar.dir/build
.PHONY : test_grammar/fast

#=============================================================================
# Target rules for targets named test_grammar_bin

# Build rule for target.
test_grammar_bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_grammar_bin
.PHONY : test_grammar_bin

# fast build rule for target.
test_grammar_bin/fast:
	$(MAKE) -f CMakeFiles/test_grammar_bin.dir/build.make CMakeFiles/test_grammar_bin.dir/build
.PHONY : test_grammar_bin/fast

#=============================================================================
# Target rules for targets named vtest_grammar

# Build rule for target.
vtest_grammar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vtest_grammar
.PHONY : vtest_grammar

# fast build rule for target.
vtest_grammar/fast:
	$(MAKE) -f CMakeFiles/vtest_grammar.dir/build.make CMakeFiles/vtest_grammar.dir/build
.PHONY : vtest_grammar/fast

#=============================================================================
# Target rules for targets named test_processor

# Build rule for target.
test_processor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_processor
.PHONY : test_processor

# fast build rule for target.
test_processor/fast:
	$(MAKE) -f CMakeFiles/test_processor.dir/build.make CMakeFiles/test_processor.dir/build
.PHONY : test_processor/fast

#=============================================================================
# Target rules for targets named vtest_processor

# Build rule for target.
vtest_processor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vtest_processor
.PHONY : vtest_processor

# fast build rule for target.
vtest_processor/fast:
	$(MAKE) -f CMakeFiles/vtest_processor.dir/build.make CMakeFiles/vtest_processor.dir/build
.PHONY : vtest_processor/fast

include/grammar.o: include/grammar.cc.o

.PHONY : include/grammar.o

# target to build an object file
include/grammar.cc.o:
	$(MAKE) -f CMakeFiles/bparser.dir/build.make CMakeFiles/bparser.dir/include/grammar.cc.o
.PHONY : include/grammar.cc.o

include/grammar.i: include/grammar.cc.i

.PHONY : include/grammar.i

# target to preprocess a source file
include/grammar.cc.i:
	$(MAKE) -f CMakeFiles/bparser.dir/build.make CMakeFiles/bparser.dir/include/grammar.cc.i
.PHONY : include/grammar.cc.i

include/grammar.s: include/grammar.cc.s

.PHONY : include/grammar.s

# target to generate assembly for a file
include/grammar.cc.s:
	$(MAKE) -f CMakeFiles/bparser.dir/build.make CMakeFiles/bparser.dir/include/grammar.cc.s
.PHONY : include/grammar.cc.s

test/test_array.o: test/test_array.cc.o

.PHONY : test/test_array.o

# target to build an object file
test/test_array.cc.o:
	$(MAKE) -f CMakeFiles/test_array_bin.dir/build.make CMakeFiles/test_array_bin.dir/test/test_array.cc.o
.PHONY : test/test_array.cc.o

test/test_array.i: test/test_array.cc.i

.PHONY : test/test_array.i

# target to preprocess a source file
test/test_array.cc.i:
	$(MAKE) -f CMakeFiles/test_array_bin.dir/build.make CMakeFiles/test_array_bin.dir/test/test_array.cc.i
.PHONY : test/test_array.cc.i

test/test_array.s: test/test_array.cc.s

.PHONY : test/test_array.s

# target to generate assembly for a file
test/test_array.cc.s:
	$(MAKE) -f CMakeFiles/test_array_bin.dir/build.make CMakeFiles/test_array_bin.dir/test/test_array.cc.s
.PHONY : test/test_array.cc.s

test/test_grammar.o: test/test_grammar.cc.o

.PHONY : test/test_grammar.o

# target to build an object file
test/test_grammar.cc.o:
	$(MAKE) -f CMakeFiles/test_grammar_bin.dir/build.make CMakeFiles/test_grammar_bin.dir/test/test_grammar.cc.o
.PHONY : test/test_grammar.cc.o

test/test_grammar.i: test/test_grammar.cc.i

.PHONY : test/test_grammar.i

# target to preprocess a source file
test/test_grammar.cc.i:
	$(MAKE) -f CMakeFiles/test_grammar_bin.dir/build.make CMakeFiles/test_grammar_bin.dir/test/test_grammar.cc.i
.PHONY : test/test_grammar.cc.i

test/test_grammar.s: test/test_grammar.cc.s

.PHONY : test/test_grammar.s

# target to generate assembly for a file
test/test_grammar.cc.s:
	$(MAKE) -f CMakeFiles/test_grammar_bin.dir/build.make CMakeFiles/test_grammar_bin.dir/test/test_grammar.cc.s
.PHONY : test/test_grammar.cc.s

test/test_parser.o: test/test_parser.cc.o

.PHONY : test/test_parser.o

# target to build an object file
test/test_parser.cc.o:
	$(MAKE) -f CMakeFiles/test_parser_bin.dir/build.make CMakeFiles/test_parser_bin.dir/test/test_parser.cc.o
.PHONY : test/test_parser.cc.o

test/test_parser.i: test/test_parser.cc.i

.PHONY : test/test_parser.i

# target to preprocess a source file
test/test_parser.cc.i:
	$(MAKE) -f CMakeFiles/test_parser_bin.dir/build.make CMakeFiles/test_parser_bin.dir/test/test_parser.cc.i
.PHONY : test/test_parser.cc.i

test/test_parser.s: test/test_parser.cc.s

.PHONY : test/test_parser.s

# target to generate assembly for a file
test/test_parser.cc.s:
	$(MAKE) -f CMakeFiles/test_parser_bin.dir/build.make CMakeFiles/test_parser_bin.dir/test/test_parser.cc.s
.PHONY : test/test_parser.cc.s

test/test_processor.o: test/test_processor.cc.o

.PHONY : test/test_processor.o

# target to build an object file
test/test_processor.cc.o:
	$(MAKE) -f CMakeFiles/test_processor_bin.dir/build.make CMakeFiles/test_processor_bin.dir/test/test_processor.cc.o
.PHONY : test/test_processor.cc.o

test/test_processor.i: test/test_processor.cc.i

.PHONY : test/test_processor.i

# target to preprocess a source file
test/test_processor.cc.i:
	$(MAKE) -f CMakeFiles/test_processor_bin.dir/build.make CMakeFiles/test_processor_bin.dir/test/test_processor.cc.i
.PHONY : test/test_processor.cc.i

test/test_processor.s: test/test_processor.cc.s

.PHONY : test/test_processor.s

# target to generate assembly for a file
test/test_processor.cc.s:
	$(MAKE) -f CMakeFiles/test_processor_bin.dir/build.make CMakeFiles/test_processor_bin.dir/test/test_processor.cc.s
.PHONY : test/test_processor.cc.s

test/test_speed.o: test/test_speed.cc.o

.PHONY : test/test_speed.o

# target to build an object file
test/test_speed.cc.o:
	$(MAKE) -f CMakeFiles/test_speed_bin.dir/build.make CMakeFiles/test_speed_bin.dir/test/test_speed.cc.o
.PHONY : test/test_speed.cc.o

test/test_speed.i: test/test_speed.cc.i

.PHONY : test/test_speed.i

# target to preprocess a source file
test/test_speed.cc.i:
	$(MAKE) -f CMakeFiles/test_speed_bin.dir/build.make CMakeFiles/test_speed_bin.dir/test/test_speed.cc.i
.PHONY : test/test_speed.cc.i

test/test_speed.s: test/test_speed.cc.s

.PHONY : test/test_speed.s

# target to generate assembly for a file
test/test_speed.cc.s:
	$(MAKE) -f CMakeFiles/test_speed_bin.dir/build.make CMakeFiles/test_speed_bin.dir/test/test_speed.cc.s
.PHONY : test/test_speed.cc.s

test/test_speed_sse.o: test/test_speed_sse.cc.o

.PHONY : test/test_speed_sse.o

# target to build an object file
test/test_speed_sse.cc.o:
	$(MAKE) -f CMakeFiles/test_speed_sse_bin.dir/build.make CMakeFiles/test_speed_sse_bin.dir/test/test_speed_sse.cc.o
.PHONY : test/test_speed_sse.cc.o

test/test_speed_sse.i: test/test_speed_sse.cc.i

.PHONY : test/test_speed_sse.i

# target to preprocess a source file
test/test_speed_sse.cc.i:
	$(MAKE) -f CMakeFiles/test_speed_sse_bin.dir/build.make CMakeFiles/test_speed_sse_bin.dir/test/test_speed_sse.cc.i
.PHONY : test/test_speed_sse.cc.i

test/test_speed_sse.s: test/test_speed_sse.cc.s

.PHONY : test/test_speed_sse.s

# target to generate assembly for a file
test/test_speed_sse.cc.s:
	$(MAKE) -f CMakeFiles/test_speed_sse_bin.dir/build.make CMakeFiles/test_speed_sse_bin.dir/test/test_speed_sse.cc.s
.PHONY : test/test_speed_sse.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... vtest_speed_sse"
	@echo "... test_speed"
	@echo "... test_speed_sse"
	@echo "... test_speed_bin"
	@echo "... test_parser_bin"
	@echo "... test_parser"
	@echo "... vtest_array"
	@echo "... test_speed_sse_bin"
	@echo "... bparser"
	@echo "... vtest_parser"
	@echo "... test_processor_bin"
	@echo "... test_array_bin"
	@echo "... vtest_speed"
	@echo "... test_array"
	@echo "... test_grammar"
	@echo "... test_grammar_bin"
	@echo "... vtest_grammar"
	@echo "... test_processor"
	@echo "... vtest_processor"
	@echo "... include/grammar.o"
	@echo "... include/grammar.i"
	@echo "... include/grammar.s"
	@echo "... test/test_array.o"
	@echo "... test/test_array.i"
	@echo "... test/test_array.s"
	@echo "... test/test_grammar.o"
	@echo "... test/test_grammar.i"
	@echo "... test/test_grammar.s"
	@echo "... test/test_parser.o"
	@echo "... test/test_parser.i"
	@echo "... test/test_parser.s"
	@echo "... test/test_processor.o"
	@echo "... test/test_processor.i"
	@echo "... test/test_processor.s"
	@echo "... test/test_speed.o"
	@echo "... test/test_speed.i"
	@echo "... test/test_speed.s"
	@echo "... test/test_speed_sse.o"
	@echo "... test/test_speed_sse.i"
	@echo "... test/test_speed_sse.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

