/*
 * nitpick_common.cc
 * Included in the nitpick_run.cc and nitpick_generate.cc files, do not compile
 *
 *  Created on: Jan 7, 2026
 *      Author: LV
 */

#ifndef NITPICK_IDE_IGNORE
#include "parser.h" //this is here to help the IDE, header file includes are in nitpick_include.hh
#endif //NITPICK_IDE_IGNORE

using namespace bparser;

// These variable names are used in macros and/or autogenerated files. Renaming them will cause issues
std::unordered_map<double*, std::string> inv_map; //given to the print_in_cxx function to generate the file
std::unordered_map<std::string, double*> node_map; //is used by the generated file to use the same double pointers as the parser