#ifndef NITPICK_INCLUDE_HH
#define NITPICK_INCLUDE_HH

#define NITPICK_AUTOGENERATED_FILE_NAME "autogenerated.cc" //Keep the same in .gitignore

#include "parser.hh"
#include <iostream>
#include <fstream>

#endif //NITPICK_INCLUDE_HH