#include "nitpick_include.hh"

int main() {
// only get us the variables
#define NITPICK_INCLUDE_ONLY
#include "nitpick_def.cc" //include all the variables used to generate the file

#include NITPICK_AUTOGENERATED_FILE_NAME

	ProcessorBase* processor = ProcessorBase::create_processor(se, max_vec_size, bparser::get_simd_size(), nullptr);

	std::vector<uint> subset = { 0, 1 }; //ctverice doubluu

	processor->set_subset(subset);
	processor->run();

	std::cout << "Result: \n";

	// Result in the 'vres' value space.
	std::cout << print_vec(vres, vres_size);
}