#ifndef NITPICK_INCLUDE_HH
#define NITPICK_INCLUDE_HH

#define NITPICK_FALLBACK_DEF_FILE_NAME "example_def.hh"
#define NITPICK_AUTOGENERATED_FILE_NAME "autogenerated.hh"

#ifndef NITPICK_DEF_FILE
# ifdef DEF_FILE
#  define NITPICK_DEF_FILE DEF_FILE
# else
#  define NITPICK_DEF_FILE NITPICK_FALLBACK_DEF_FILE_NAME
# endif
#endif

#ifndef NITPICK_GEN_FILE
# ifdef GEN_FILE
#  define NITPICK_GEN_FILE GEN_FILE
# else
#  define NITPICK_GEN_FILE NITPICK_AUTOGENERATED_FILE_NAME
# endif
#endif

#include "test_tools.hh"
#include "parser.hh"
#include <iostream>
#include "exprcase.hh"

//void def(ExprCase c);
//ExpressionDAG gen(const NodeMap& node_map);


#endif //NITPICK_INCLUDE_HH