#ifndef NITPICK_INCLUDE_HH
#define NITPICK_INCLUDE_HH

#define NITPICK_AUTOGENERATED_FILE_NAME "autogenerated.cc" //Keep the same in .gitignore

#define P_SET_(TYPE, NAME, SHAPE, POINTER)											\
		Array NAME##_array = Array::value(POINTER, max_vec_size, SHAPE);				\
																					\
		for (MultiIdx idx(NAME##_array.range()); idx.valid(); idx.inc_src()) {		\
			std::string var_name = get_var_name(#NAME, idx.indices());				\
			inv_map[NAME##_array[idx]->values_] = var_name;									\
			node_map[var_name] = NAME##_array[idx]->values_;						\
		}																			\
		p.set_##TYPE(#NAME, SHAPE, POINTER);

#define P_SET_VARIABLE(NAME, SHAPE, POINTER) P_SET_(variable, NAME, SHAPE, POINTER)
//#define P_SET_CONSTANT(NAME, SHAPE, POINTER) P_SET_(constant, NAME, SHAPE, POINTER)
#define P_SET_VAR_COPY(NAME, SHAPE, POINTER) P_SET_(var_copy, NAME, SHAPE, POINTER)

#include "test_tools.hh"
#include "parser.hh"
#include <iostream>
#include <fstream>

std::string get_var_name(const std::string & name, const bparser::MultiIdx::VecUint & indices);

// v1, (1,2,3) => "v1__1_2_3"
std::string get_var_name(const std::string& name, const bparser::MultiIdx::VecUint& indices) {
	bparser::MultiIdx::VecUint::size_type size(indices.size());

	std::ostringstream result;
	result << name;
	result << "__";
	for (bparser::MultiIdx::VecUint::size_type i = 0; i < size; i++) {
		result << indices.at(i);
		if (i != size - 1) {
			result << '_';
		}
	}
	return result.str();
}


#endif //NITPICK_INCLUDE_HH