#include "nitpick_include.hh"
#include <filesystem>

int main() {

#define NITPICK_INCLUDE_ONLY
#include "nitpick_def.cc"

	// Compile the expression into internal processor.
	p.compile();

	ExpressionDAG dag(p.result_array().elements());
	//dag.print_in_dot2();

	std::ofstream file(NITPICK_AUTOGENERATED_FILE_NAME);
	file << DagPrinter(dag).print_in_cxx(inv_map);
	file.close();
	std::cout << "File " << std::filesystem::current_path() << " " << NITPICK_AUTOGENERATED_FILE_NAME << " created";
}