#include "nitpick_include.hh"

int main() {
// only get us the variables
#define NITPICK_INCLUDE_ONLY
#include "nitpick_def.cc" //include all the variables used to generate the file

#include NITPICK_AUTOGENERATED_FILE_NAME

	ProcessorBase* processor = ProcessorBase::create_processor(se, vec_size, bparser::get_simd_size(), nullptr);

	std::vector<uint> subset = { 0, 1 };

	processor->set_subset(subset);
	processor->run();

	// Result in the 'vres' value space.
	//std::cout << print_vec(vres, 3 * vec_size);
}