#include "nitpick_include.hh"
#include <chrono>
#include "scalar_node.hh"
// only get us the variables
#define NITPICK_IDE_IGNORE

using namespace bparser;
	//include all the variables used to generate the file
#include NITPICK_DEF_FILE
	//include the generated file
#include NITPICK_GEN_FILE

int main() {
	const uint N = 1048576; //2^20 //1073741824U; //2^30

	const uint max_vec_size = 2000;
	const size_t buffer_size = sizeof(double) * N * 32;

	std::cout << "Buffer size: " << buffer_size << std::endl;
	int simd_size = bparser::get_simd_size();
	std::cout << "SIMD size: " << simd_size << std::endl;

	void* buffer = ::operator new(buffer_size);
	ExprCase exprcase(max_vec_size, (void*)buffer, buffer_size);

	def(exprcase);

	if (exprcase.get_expression().empty()) {
		Throw() << "No expression was set!";
	}

	std::vector<uint> vec_sizes({ 16U, 64U, 256U, 1024U });

	PatchArenaPtr arena = exprcase.get_patch_arena();
	for (uint vec_size : vec_sizes) {

		uint n_repeats = N / vec_size;

		std::cout << "Running \"" << exprcase.get_expression() << "\" " << n_repeats << "x for vec_size: " << vec_size << std::endl;

		//exprcase.allocate(vec_size);
		exprcase.allocate(N);

		Parser& p = exprcase.get_parser();
		p.compile();
		auto nodes = p.result_array().elements();
		std::vector<ScalarNodePtr> value_nodes = {};
		std::vector<ScalarNodePtr> val_copy_nodes = {};
		for (uint i = 0; i < nodes.size(); i++) {
			ScalarNodePtr n = nodes[i];
			if (n->result_storage == value) {
				value_nodes.push_back(n);
			}
			else if (n->result_storage == value_copy) {
				val_copy_nodes.push_back(n);
			}
		}

		auto dangerous_shift = [&](uint a) {
			for (auto n : value_nodes) {
				n->values_ += a;
			}
			for (auto n : val_copy_nodes) {
				details::ValueCopyNode& vcn = dynamic_cast<details::ValueCopyNode&>(*n);
				vcn.source_ptr_ += a;
			}
		};

		//Get autogenerated dag;
		ExpressionDAG se = gen(exprcase.get_node_map());

		ProcessorBase* processor = ProcessorBase::create_processor(se, vec_size, simd_size, nullptr); //don't pass the arena, processor will create its own optimized one

		std::vector<uint> subset(std::ceil(vec_size / (float)simd_size)); //ex: 32/4 = 8 => 
		std::iota(subset.begin(), subset.end(), 0);					// => {0, 1, 2, 3, 4, 5, 6, 7}
		processor->set_subset(subset); //all subsets

		auto start_time = std::chrono::high_resolution_clock::now();
		for (uint i_rep = 0; i_rep < n_repeats; i_rep++) {
			processor->run();
			dangerous_shift(vec_size);
		}
		auto end_time = std::chrono::high_resolution_clock::now();

		double time = std::chrono::duration_cast<std::chrono::duration<double>>(end_time - start_time).count();
		std::cout << std::fixed << "Finished in " << time << std::defaultfloat << std::endl;

		//Use lower vec_size for this print
		//std::cout << print_vec(exprcase.get_result_ptr(), exprcase.get_result_ptr_size()) << std::endl;

		processor->arena_ = nullptr; //remove the only shared_ptr of arena -> arena gets deleted -> processor removed
		exprcase.deallocate();
	} //for


	//std::cout << "Result: \n";

	// Result in the 'vres' value space.
	//std::cout << print_vec(vres, vres_size);
	

	::operator delete(buffer);

} //main