#ifndef TESTCASE_HH
#define TESTCASE_HH

#include "nitpick_include.hh"
#include <chrono>

// only get us the variables
#define NITPICK_IDE_IGNORE

using namespace bparser;
//include all the variables used to generate the file
#include NITPICK_DEF_FILE
	//include the generated file
#include NITPICK_GEN_FILE

class TestCase
{
public:
	static const uint N = 1048576;
protected:
	uint vec_size;
	uint allocation_vec_size;

	void* buffer;
	size_t buffer_size;
	int simd_size;

	ExprCase exprcase;
	ProcessorBase* processor;


protected:
	virtual VariableAllocationEnum getAllocMethod() const {	return KeepDefault;	}
	virtual std::string getTestCaseIdentifier() const {	return "TestCase";	}

	virtual ProcessorBase* create_processor(details::ExpressionDAG& se) {
		return ProcessorBase::create_processor(se, vec_size, simd_size, nullptr);
	}

	virtual void before_timing() {
		;
	}

	virtual void time_case(uint n_repeats) {
		auto start_time = std::chrono::high_resolution_clock::now();
		for (uint i_rep = 0; i_rep < n_repeats; i_rep++) {
			processor->run();
			//dangerous_shift(vec_size);
		}
		auto end_time = std::chrono::high_resolution_clock::now();

		double time = std::chrono::duration_cast<std::chrono::duration<double>>(end_time - start_time).count();
		std::cout << std::fixed << "[" << getTestCaseIdentifier() << "] " << "Finished in " << time << std::defaultfloat << std::endl;
	}

public:

	TestCase(uint vec_size, uint allocation_vec_size, void* buffer, size_t buffer_size) : 
		vec_size(vec_size),
		allocation_vec_size(allocation_vec_size),
		buffer(buffer),
		buffer_size(buffer_size),
		simd_size(bparser::get_simd_size()),
		exprcase(ExprCase(vec_size, (void*)buffer, buffer_size))
	{
		;
	}

	TestCase(uint vec_size, void* buffer, size_t buffer_size) : TestCase(vec_size, vec_size, buffer, buffer_size) 
	{ ; }

	void run() {
			
			def(exprcase);

			if (exprcase.get_expression().empty()) {
				Throw() << "No expression was set!";
			}

			uint n_repeats = N / vec_size;

			std::cout << "[" << getTestCaseIdentifier() << "] " << "Running \"" << exprcase.get_expression() << "\" " << n_repeats << "x for vec_size: " << vec_size << std::endl;

			globalVariableAllocationMethod = getAllocMethod();
			exprcase.allocate(allocation_vec_size);

			before_timing();

			//Get autogenerated dag;
			ExpressionDAG se = gen(exprcase.get_node_map());

			processor = create_processor(se);

			std::vector<uint> subset(std::ceil(vec_size / (float)simd_size)); //ex: 32/4 = 8 => 
			std::iota(subset.begin(), subset.end(), 0);					// => {0, 1, 2, 3, 4, 5, 6, 7}
			processor->set_subset(subset); //all subsets

			time_case(n_repeats);

			//Use lower vec_size for this print
			//std::cout << print_vec(exprcase.get_result_ptr(), exprcase.get_result_ptr_size()) << std::endl;

			processor->arena_ = nullptr; //remove the only shared_ptr of arena -> arena gets deleted -> processor removed
			exprcase.deallocate();
	}

};

//Variables in the same arena as processor, no shifting
class EfficientTestCase : public TestCase {
	using TestCase::TestCase;
	std::string getTestCaseIdentifier() const override { return "EfficientTestCase"; }

	ProcessorBase* create_processor(details::ExpressionDAG& se) override{
		return ProcessorBase::create_processor(se, vec_size, simd_size, exprcase.get_patch_arena());
	}
};

class EfficientTestCaseForceVariable : public EfficientTestCase {
	using EfficientTestCase::EfficientTestCase;
	std::string getTestCaseIdentifier() const override { return "EfficientTestCaseForceVariable"; }
	VariableAllocationEnum getAllocMethod() const override { return ForceVariable; }
};




//Variables in different arena to processor's, allocate N,shift by vec_size
class ShiftingTestCase : public TestCase {
	std::string getTestCaseIdentifier() const override { return "ShiftingTestCase"; }

	using ValueCopyNodePtr = std::shared_ptr<bparser::details::ValueCopyNode>;

	std::vector<ScalarNodePtr> value_nodes{};
	std::vector<ValueCopyNodePtr> val_copy_nodes{};

public:
	ShiftingTestCase(uint vec_size, uint allocation_vec_size, void* buffer, size_t buffer_size) : TestCase(vec_size, allocation_vec_size, buffer, buffer_size) {
		;
	}
	ShiftingTestCase(uint vec_size, void* buffer, size_t buffer_size) : TestCase(vec_size, N, buffer, buffer_size) {
		;
	}
protected:

	void before_timing() override {
		Parser& p = exprcase.get_parser();
		p.compile();
		auto nodes = p.result_array().elements();

		for (uint i = 0; i < nodes.size(); i++) {
			ScalarNodePtr n = nodes[i];
			if (n->result_storage == value) {
				value_nodes.push_back(n);
			}
			else if (n->result_storage == value_copy) {
				val_copy_nodes.push_back(std::dynamic_pointer_cast<details::ValueCopyNode>(n));
			}
		}
	}

	void time_case(uint n_repeats) override {
		auto start_time = std::chrono::high_resolution_clock::now();
		for (uint i_rep = 0; i_rep < n_repeats; i_rep++) {
			processor->run();
			dangerous_shift(vec_size);
		}
		auto end_time = std::chrono::high_resolution_clock::now();

		double time = std::chrono::duration_cast<std::chrono::duration<double>>(end_time - start_time).count();
		std::cout << std::fixed << "[" << getTestCaseIdentifier() << "] " << "Finished in " << time << std::defaultfloat << std::endl;
	}

protected:
	void dangerous_shift(uint a) {
		for (auto n : value_nodes) {
			n->values_ += a;
		}
		for (auto n : val_copy_nodes) {
			n->source_ptr_ += a;
		}
	}
};

class ShiftingTestCaseForceVariable : public ShiftingTestCase {
	using ShiftingTestCase::ShiftingTestCase;
	std::string getTestCaseIdentifier() const override { return "ShiftingTestCaseForceVariable"; }
	VariableAllocationEnum getAllocMethod() const override { return ForceVariable; }
};

class ShiftingTestCaseForceCopy : public ShiftingTestCase {
	using ShiftingTestCase::ShiftingTestCase;
	std::string getTestCaseIdentifier() const override { return "ShiftingTestCaseForceCopy"; }
	VariableAllocationEnum getAllocMethod() const override { return ForceVarCopy; }
};

#endif //TESTCASE_HH