//AUTOGENERATED This file has been autogenerated by bparser::details::DagPrinter::print_in_cxx
// Apr 12 2026 18:39:24

#ifndef NITPICK_IDE_IGNORE
#include "nitpick_common.hh"
#include "nitpick_include.hh"
using namespace bparser;
using namespace bparser::details;
#endif //NITPICK_IDE_IGNORE //This is here only to stop any IDE warnings
ExpressionDAG gen(const NodeMap& node_map){ //Do not rename this function, it is used later in the nitpick_run.cc file

ScalarNodePtr Value_14__2 = create_variable_node(node_map.at("u[1]"),Variable);
ScalarNodePtr Value_13__2 = create_variable_node(node_map.at("v[2]"),Variable);
ScalarNodePtr mul_12__3 = ScalarNode::create<_mul_>(Value_14__2, Value_13__2);
ScalarNodePtr Value_11__2 = create_variable_node(node_map.at("u[2]"),Variable);
ScalarNodePtr Value_10__2 = create_variable_node(node_map.at("v[1]"),Variable);
ScalarNodePtr mul_9__3 = ScalarNode::create<_mul_>(Value_11__2, Value_10__2);
ScalarNodePtr sub_8__4 = ScalarNode::create<_sub_>(mul_12__3, mul_9__3);
ScalarNodePtr Value_7__2 = create_variable_node(node_map.at("v[0]"),Variable);
ScalarNodePtr mul_6__3 = ScalarNode::create<_mul_>(Value_11__2, Value_7__2);
ScalarNodePtr Value_5__2 = create_variable_node(node_map.at("u[0]"),Variable);
ScalarNodePtr mul_4__3 = ScalarNode::create<_mul_>(Value_5__2, Value_13__2);
ScalarNodePtr sub_3__4 = ScalarNode::create<_sub_>(mul_6__3, mul_4__3);
ScalarNodePtr mul_2__3 = ScalarNode::create<_mul_>(Value_5__2, Value_10__2);
ScalarNodePtr mul_1__3 = ScalarNode::create<_mul_>(Value_14__2, Value_7__2);
ScalarNodePtr sub_0__4 = ScalarNode::create<_sub_>(mul_2__3, mul_1__3);


ScalarNodePtr r0 = ScalarNode::create_result(sub_8__4, node_map.at("_result_[0]"));
ScalarNodePtr r1 = ScalarNode::create_result(sub_3__4, node_map.at("_result_[1]"));
ScalarNodePtr r2 = ScalarNode::create_result(sub_0__4, node_map.at("_result_[2]"));
ExpressionDAG se({r0, r1, r2});

return se;
} //gen
