//AUTOGENERATED This file has been autogenerated by bparser::details::DagPrinter::print_in_cxx
// Mar 22 2026 21:51:21

#ifndef NITPICK_IDE_IGNORE
#include "nitpick_common.hh"
#include "nitpick_include.hh"
using namespace bparser;
using namespace bparser::details;
#endif //NITPICK_IDE_IGNORE //This is here only to stop any IDE warnings
ExpressionDAG gen(const NodeMap& node_map){ //Do not rename this function, it is used later in the nitpick_run.cc file

ScalarNodePtr Const_51__1 = ScalarNode::create_const(1);
ScalarNodePtr Value_50__2 = create_variable_node(node_map.at("m3[1,1]"),Variable);
ScalarNodePtr Value_49__2 = create_variable_node(node_map.at("m3[2,2]"),Variable);
ScalarNodePtr mul_48__3 = ScalarNode::create<_mul_>(Value_50__2, Value_49__2);
ScalarNodePtr Value_47__2 = create_variable_node(node_map.at("m3[1,2]"),Variable);
ScalarNodePtr Value_46__2 = create_variable_node(node_map.at("m3[2,1]"),Variable);
ScalarNodePtr mul_45__3 = ScalarNode::create<_mul_>(Value_47__2, Value_46__2);
ScalarNodePtr sub_44__3 = ScalarNode::create<_sub_>(mul_48__3, mul_45__3);
ScalarNodePtr Value_43__2 = create_variable_node(node_map.at("m3[0,0]"),Variable);
ScalarNodePtr mul_42__3 = ScalarNode::create<_mul_>(sub_44__3, Value_43__2);
ScalarNodePtr Value_41__2 = create_variable_node(node_map.at("m3[0,2]"),Variable);
ScalarNodePtr mul_40__3 = ScalarNode::create<_mul_>(Value_46__2, Value_41__2);
ScalarNodePtr Value_39__2 = create_variable_node(node_map.at("m3[0,1]"),Variable);
ScalarNodePtr mul_38__3 = ScalarNode::create<_mul_>(Value_49__2, Value_39__2);
ScalarNodePtr sub_37__3 = ScalarNode::create<_sub_>(mul_40__3, mul_38__3);
ScalarNodePtr Value_36__2 = create_variable_node(node_map.at("m3[1,0]"),Variable);
ScalarNodePtr mul_35__3 = ScalarNode::create<_mul_>(sub_37__3, Value_36__2);
ScalarNodePtr add_34__3 = ScalarNode::create<_add_>(mul_42__3, mul_35__3);
ScalarNodePtr mul_33__3 = ScalarNode::create<_mul_>(Value_39__2, Value_47__2);
ScalarNodePtr mul_32__3 = ScalarNode::create<_mul_>(Value_41__2, Value_50__2);
ScalarNodePtr sub_31__3 = ScalarNode::create<_sub_>(mul_33__3, mul_32__3);
ScalarNodePtr Value_30__2 = create_variable_node(node_map.at("m3[2,0]"),Variable);
ScalarNodePtr mul_29__3 = ScalarNode::create<_mul_>(sub_31__3, Value_30__2);
ScalarNodePtr add_28__3 = ScalarNode::create<_add_>(add_34__3, mul_29__3);
ScalarNodePtr div_27__3 = ScalarNode::create<_div_>(Const_51__1, add_28__3);
ScalarNodePtr mul_26__4 = ScalarNode::create<_mul_>(sub_44__3, div_27__3);
ScalarNodePtr mul_25__4 = ScalarNode::create<_mul_>(sub_37__3, div_27__3);
ScalarNodePtr mul_24__4 = ScalarNode::create<_mul_>(sub_31__3, div_27__3);
ScalarNodePtr mul_23__3 = ScalarNode::create<_mul_>(Value_47__2, Value_30__2);
ScalarNodePtr mul_22__3 = ScalarNode::create<_mul_>(Value_36__2, Value_49__2);
ScalarNodePtr sub_21__3 = ScalarNode::create<_sub_>(mul_23__3, mul_22__3);
ScalarNodePtr mul_20__4 = ScalarNode::create<_mul_>(sub_21__3, div_27__3);
ScalarNodePtr mul_19__3 = ScalarNode::create<_mul_>(Value_49__2, Value_43__2);
ScalarNodePtr mul_18__3 = ScalarNode::create<_mul_>(Value_30__2, Value_41__2);
ScalarNodePtr sub_17__3 = ScalarNode::create<_sub_>(mul_19__3, mul_18__3);
ScalarNodePtr mul_16__4 = ScalarNode::create<_mul_>(sub_17__3, div_27__3);
ScalarNodePtr mul_15__3 = ScalarNode::create<_mul_>(Value_41__2, Value_36__2);
ScalarNodePtr mul_14__3 = ScalarNode::create<_mul_>(Value_43__2, Value_47__2);
ScalarNodePtr sub_13__3 = ScalarNode::create<_sub_>(mul_15__3, mul_14__3);
ScalarNodePtr mul_12__4 = ScalarNode::create<_mul_>(sub_13__3, div_27__3);
ScalarNodePtr mul_11__3 = ScalarNode::create<_mul_>(Value_36__2, Value_46__2);
ScalarNodePtr mul_10__3 = ScalarNode::create<_mul_>(Value_50__2, Value_30__2);
ScalarNodePtr sub_9__3 = ScalarNode::create<_sub_>(mul_11__3, mul_10__3);
ScalarNodePtr mul_8__4 = ScalarNode::create<_mul_>(sub_9__3, div_27__3);
ScalarNodePtr mul_7__3 = ScalarNode::create<_mul_>(Value_30__2, Value_39__2);
ScalarNodePtr mul_6__3 = ScalarNode::create<_mul_>(Value_46__2, Value_43__2);
ScalarNodePtr sub_5__3 = ScalarNode::create<_sub_>(mul_7__3, mul_6__3);
ScalarNodePtr mul_4__4 = ScalarNode::create<_mul_>(sub_5__3, div_27__3);
ScalarNodePtr mul_3__3 = ScalarNode::create<_mul_>(Value_43__2, Value_50__2);
ScalarNodePtr mul_2__3 = ScalarNode::create<_mul_>(Value_39__2, Value_36__2);
ScalarNodePtr sub_1__3 = ScalarNode::create<_sub_>(mul_3__3, mul_2__3);
ScalarNodePtr mul_0__4 = ScalarNode::create<_mul_>(sub_1__3, div_27__3);


ScalarNodePtr r0 = ScalarNode::create_result(mul_26__4, node_map.at("_result_[0,0]"));
ScalarNodePtr r1 = ScalarNode::create_result(mul_25__4, node_map.at("_result_[0,1]"));
ScalarNodePtr r2 = ScalarNode::create_result(mul_24__4, node_map.at("_result_[0,2]"));
ScalarNodePtr r3 = ScalarNode::create_result(mul_20__4, node_map.at("_result_[1,0]"));
ScalarNodePtr r4 = ScalarNode::create_result(mul_16__4, node_map.at("_result_[1,1]"));
ScalarNodePtr r5 = ScalarNode::create_result(mul_12__4, node_map.at("_result_[1,2]"));
ScalarNodePtr r6 = ScalarNode::create_result(mul_8__4, node_map.at("_result_[2,0]"));
ScalarNodePtr r7 = ScalarNode::create_result(mul_4__4, node_map.at("_result_[2,1]"));
ScalarNodePtr r8 = ScalarNode::create_result(mul_0__4, node_map.at("_result_[2,2]"));
ExpressionDAG se({r0, r1, r2, r3, r4, r5, r6, r7, r8});

return se;
} //gen
