/*
 * dag_printer.hh
 * 
 * Implements tostring/print methods for ExpressionDAG in various formats:
 * DOT (Graphviz)
 * C++
 *
 *  Created on: Jan 05, 2026
 *      Author: LV
 */


#ifndef DAG_PRINTER_HH
#define DAG_PRINTER_HH

#include "expression_dag.hh"

namespace bparser {
namespace details {

	class DagPrinter {
	private:
		// Backward topologicaly sorted nodes; results first, inputs last
		bparser::details::ExpressionDAG::NodeVec sorted;

		// Holds the names of every node
		std::map<ScalarNodePtr, std::string> node_names;

	public:

		DagPrinter(ExpressionDAG& dag)
			:sorted(dag.sort_nodes()) 
		{
			name_nodes();
		}

		DagPrinter(const ExpressionDAG::NodeVec& vec)
			: sorted(vec)
		{
			name_nodes();
		}

		typedef std::pair<std::string, MultiIdx::VecUint> InvDotNameAndIndices;
		typedef std::map<ScalarNodePtr, InvDotNameAndIndices> InvDotMap;
		typedef std::unordered_map<double*, std::string> CXXVarMap;



	private:
		void name_nodes() {
			for (uint i = 0; i < sorted.size(); ++i) {
				ScalarNodePtr node = sorted[i];
				node_names[node] = node->op_name_ + "_" + std::to_string(i) + "__" + std::to_string(node->result_storage);
			}
		}

	public:
		/*
		* Print ScalarExpression graph in the common dot format.
		* Useful for understanding the DAG.
		*/
		void print_in_dot2() const {
			print_in_dot2(InvDotMap());
		}

		/*
		* Print ScalarExpression graph in the common dot format.
		* Useful for understanding the DAG. Using the parser's map of var. Name -> Array find the inverse ScalarNodePtr -> var. Name
		*/
		void print_in_dot2(const std::map<std::string, bparser::Array>& symbols) const {
			print_in_dot2(create_inverse_map(symbols));
		}

		/*
		* Print ScalarExpression graph in the common dot format.
		* Useful for understanding the DAG. Using the map of ScalarNodePtr -> variableName
		*/
		void print_in_dot2(const InvDotMap& names) const {

			std::cout << "\n" << "----- begin cut here -----" << "\n";
			std::cout << "digraph Expr {" << "\n";

			std::cout << "/* definitions */" << "\n";

			std::cout << "edge [dir=back]" << "\n";
			for (uint i = 0; i < sorted.size(); ++i) {
				_print_dot_node_definition(sorted[i], names);
			}
			std::cout << "/* end of definitions */" << "\n";

			for (uint i = 0; i < sorted.size(); ++i) {
				for (uint in = 0; in < sorted[i]->n_inputs_; ++in) {
					std::cout << "    ";
					std::cout << _get_dot_node_id(sorted[i]);
					std::cout << "\n -> ";
					std::cout << _get_dot_node_id(sorted[i]->inputs_[in]);
					std::cout << "\n\n";
				}
			}
			std::cout << "}" << "\n";
			std::cout << "-----  end cut here  -----" << "\n";
			std::cout.flush();
		}


		std::string print_in_cxx(const CXXVarMap& map) {
			std::ostringstream result;
			ExpressionDAG::NodeVec result_nodes;
			//TODO: Make a function returning se and getting node_map
			result << "//AUTOGENERATED This file has been autogenerated by bparser::details::DagPrinter::print_in_cxx" << "\n";
			result << "// " << __DATE__ << " " << __TIME__ << "\n";
			result << "\n";
			result << "#ifndef NITPICK_IDE_IGNORE" << "\n";
			result << "#include \"nitpick_common.hh\"" << "\n";
			result << "#include \"nitpick_include.hh\"" << "\n";
			result << "using namespace bparser;" << "\n";
			result << "using namespace bparser::details;" << "\n";
			result << "#endif //NITPICK_IDE_IGNORE //This is here only to stop any IDE warnings" << "\n";
			result << "ExpressionDAG gen(const NodeMap& node_map){ //Do not rename this function, it is used later in the nitpick_run.cc file" << "\n";
			result << "\n";

			//Print nodes
			for (uint i = sorted.size(); i-- > 0U; ) { // N-1,N-2,... 0

				result << _get_cxx_node_definition(sorted[i], map);
				//result << "\n";
				if (sorted[i]->result_storage == expr_result) {
					result_nodes.push_back(sorted[i]);
				}
			}
			result << "\n\n";
			//Print results
			for (uint i = 0U; i < result_nodes.size(); ++i) {
				result << "ScalarNodePtr " << "r" << i << " = " << _get_cxx_result(result_nodes[i], map);
			}
			//Print final dag
			result << "ExpressionDAG se({";
			for (uint i = 0U; i < result_nodes.size(); ++i) {
				result << "r" << i;
				if (i < result_nodes.size() - 1) {
					result << ", ";
				}
			}
			result << "});" << "\n";
			result << "\n";
			result << "return se;" << "\n";

			result << "} //gen" << "\n";

			//std::cout << result.str();
			return result.str();

		}

		//Create a map of ScalarNodePtr -> (variable name, indices)
		InvDotMap create_inverse_map(const std::map<std::string, bparser::Array>& symbols) const {
			InvDotMap inv_map;
			if (symbols.empty()) return inv_map;
			for (const auto& s : symbols)
			{
				for (MultiIdx idx(s.second.range()); idx.valid(); idx.inc_src()) {
					inv_map[s.second[idx]] = InvDotNameAndIndices(s.first, idx.indices());
				}
				/*for (const auto& n : s.second.elements()) {
					inv_map[n] = InvDotNameAndIndices(s.first, s.second.shape().empty());
				}*/
			}
			return inv_map;
		}

	protected:
		std::string _get_node_id(const ScalarNodePtr& node) const {
			return node_names.at(node);
		}

		//Print the vertice identifier for dot
		std::string _get_dot_node_id(const ScalarNodePtr& node) const {
			return _get_node_id(node);
		}

		//Print how the vertice should look in dot
		void _print_dot_node_definition(const ScalarNodePtr& node, const InvDotMap& invmap) const {
			std::cout << _get_dot_node_id(node);
			std::cout << ' ';

			switch (node->result_storage) {
			case ResultStorage::constant: {				// Constant
				std::cout << "[shape=circle,";

				try { //If the constant has a name
					std::string name(invmap.at(node).first);
					const MultiIdx::VecUint indices(invmap.at(node).second);
					bool scalar(indices.empty());
					if (scalar) {
						std::cout << "label=\"" << name << '=' << *node->values_ << '\"';
					}
					else {
						MultiIdx::VecUint::size_type size(indices.size());
						std::cout << "label=\"" << name << "[";
						for (MultiIdx::VecUint::size_type i = 0; i < size; i++) {
							std::cout << indices.at(i);
							if (i != size - 1) {
								std::cout << ',';
							}
						}
						std::cout << "]";
						std::cout << '=' << *node->values_ << '\"';
					}
					std::cout << ", group = \"" << name << '\"';
				}
				catch (const std::out_of_range&) { //No name
					std::cout << "label=\"" << "const " << *node->values_ << '"';
				}
				std::cout << "]" << std::endl;
				break;
			}

			case ResultStorage::constant_bool: {		//Constant bool
				std::cout << "[shape=circle,";

				try { //If the constant has a name
					std::string name(invmap.at(node).first);
					const MultiIdx::VecUint indices(invmap.at(node).second);
					bool scalar(indices.empty());
					if (scalar) {
						std::cout << "label=\"" << name << '=' << *node->values_ << '\"';
					}
					else {
						MultiIdx::VecUint::size_type size(indices.size());
						std::cout << "label=\"" << name << "[";
						for (MultiIdx::VecUint::size_type i = 0; i < size; i++) {
							std::cout << indices.at(i);
							if (i != size - 1) {
								std::cout << ',';
							}
						}
						std::cout << "]";
						std::cout << '=' << *node->values_ << '\"';
					}
					std::cout << ", group = \"" << name << '\"';
				}
				catch (const std::out_of_range&) { //No name
					std::cout << "label=\"" << "const " << *node->values_ << '"';
				}
				std::cout << "]" << std::endl;
				break;
			}

			case ResultStorage::expr_result: {			//Result
				std::cout << "[shape=box,label=\"" << node->op_name_ << " [" << node->result_idx_ << "]" << "\"]" << std::endl;
				break;
			}

			case ResultStorage::value: {				// Value
				std::cout << "[shape=circle,";
				try {
					std::string name(invmap.at(node).first);
					const MultiIdx::VecUint indices(invmap.at(node).second);
					bool scalar(indices.empty());
					if (scalar) {
						std::cout << "label=\"" << name << '"';
					}
					else {
						MultiIdx::VecUint::size_type size(indices.size());
						std::cout << "label=\"" << name << "[";
						for (MultiIdx::VecUint::size_type i = 0; i < size; i++) {
							std::cout << indices.at(i);
							if (i != size - 1) {
								std::cout << ',';
							}
						}
						std::cout << "]\"";
					}
					std::cout << ",group=\"" << name << '"';
				}
				catch (const std::out_of_range&) {
					std::cout << "label=<<I>var</I>>";
				}

				std::cout << "]" << std::endl;
				break;
			}

			case ResultStorage::value_copy: {			//Value copy
				std::cout << "[shape=circle,";
				try {
					std::string name(invmap.at(node).first);
					MultiIdx::VecUint indices(invmap.at(node).second);
					bool scalar(indices.empty());
					if (scalar) {
						std::cout << "label=\"" << name << '"';
					}
					else {
						MultiIdx::VecUint::size_type size(indices.size());
						std::cout << "label=\"" << name << "[";
						for (MultiIdx::VecUint::size_type i = 0; i < size; i++) {
							std::cout << indices.at(i);
							if (i != size - 1) {
								std::cout << ',';
							}
						}
						std::cout << "]\"";
					}
					std::cout << ",group=\"" << name << '"';
				}
				catch (const std::out_of_range&) {
					std::cout << "label=<<I>var_cp</I>>";
				}
				std::cout << "]" << std::endl;
				break;
			}

			default: {									//Temporary & other
				std::cout << "[label=\"" << node->op_name_ << "\"]" << std::endl;
				break;
			}
			} //switch
		}


		std::string _get_cxx_node_id(const ScalarNodePtr& node) const {
			return _get_node_id(node);
		}

		std::string _get_cxx_input_ids(const ScalarNodePtr& node) const {
			std::string result;
			for (uint in = 0; in < node->n_inputs_; ++in) {
				result += _get_cxx_node_id(node->inputs_[in]);
				if (in < node->n_inputs_ - 1) {
					result += ", ";
				}
			}
			return result;
		}

		std::string _get_cxx_node_definition(const ScalarNodePtr& node, const CXXVarMap& map) const {
			std::ostringstream result;

			result << "ScalarNodePtr " << _get_cxx_node_id(node) << " = ";
			switch (node->result_storage)
			{
			case ResultStorage::constant: {
				if (map.count(node->values_) == 1) { //this will not work, each Array::const has its own pointers
					result << "create_variable_node(node_map.at(\"" << map.at(node->values_) << "\"),Const);\n";
				}
				else {
					result << "ScalarNode::create_const(" << *node->values_ << ");\n";
				}
				break;
			}
			case ResultStorage::constant_bool: {
				if (map.count(node->values_) == 1) {
					result << "create_variable_node(node_map.at(\"" << map.at(node->values_) << "\"),ConstBool);\n";
				}
				else {
					result << "ScalarNode::create_const_bool(" << *node->values_ << ");\n";
				}
				break;
			}
			case ResultStorage::value: {
				result << "create_variable_node(node_map.at(\"" << map.at(node->values_) << "\"),Variable);\n";
				break;
			}
			case ResultStorage::value_copy: {
				result << "create_variable_node(node_map.at(\"" << map.at(node->values_) << "\"),VarCopy);\n";
				break;
			}
			case ResultStorage::expr_result:
			case ResultStorage::temporary: {
				result << "ScalarNode::create<_" << node->op_name_ << "_>(" << _get_cxx_input_ids(node) << ");\n";
				break;
			}
			/*case ResultStorage::expr_result: {
				result << "ScalarNode::create_result(" << _get_cxx_node_id(node->inputs_[0]) << ", " << "???" << ");\n";
				break;
			}*/
			default:
				break;
			}
			return result.str();
		}

		std::string _get_cxx_result(const ScalarNodePtr& node, const CXXVarMap& map) const {
			return "ScalarNode::create_result(" + _get_cxx_node_id(node) + ", node_map.at(\"" + map.at(node->values_) + "\"));\n";
		}

	}; //DagPrinter
} //details
} //bparser

#endif //DAG_PRINTER_HH