/*
* Prepare an environment for both DAG generation and then subsequent running
*/


#ifndef NITPICK_IDE_IGNORE
#include "nitpick_include.hh"
#endif //NITPICK_IDE_IGNORE



#ifndef NITPICK_IDE_IGNORE
int main() {
#endif //NITPICK_IDE_IGNORE

	// Define own value vectors, preferably aligned.
	// These variable names are used in macros and/or autogenerated files. Renaming them will cause issues
	constexpr uint vec_size = 8;
	constexpr uint max_vec_size = vec_size;



	//Memory allocation

	double v1[vec_size * 3];
	for (uint i = 0; i < vec_size * 3; ++i) {
		v1[i] = i;
	}
	double v2[vec_size * 3];
	for (uint i = 0; i < vec_size * 3; ++i) {
		v2[i] = 2;
	}
	constexpr int vres_size = vec_size * 3;
	double vres[vres_size];
	for (uint i = 0; i < vres_size; ++i) {
		vres[i] = NAN;
	}

	// Create parser, give the size of the value spaces.
	// That is maximal allocated space. Actual values and 
	// active subset can be changed between evaluations of the expression.
	// This variable name is used in macros and/or autogenerated files. Renaming it will cause issues
	Parser p(max_vec_size);


	// parse an expression.
	p.parse("1 * v1 + cs1 * v2");

	// "cs1" constant with shape {}, i.e. scalar and values {2}.
	P_SET_CONSTANT(cs1, {}, {2});
	// "cv1" vector constant with shape {3}
	P_SET_CONSTANT(cv1, {3}, ARG({1, 2, 3}));
	// "v1" variable with shape {3}; v1 is pointer to the value space
	P_SET_VARIABLE(v1, { 3 }, v1);
	P_SET_VARIABLE(v2, { 3 }, v2);
	// Set the result variable (the last line of the expression)
	P_SET_VARIABLE(_result_, { 3 }, vres);

#ifndef NITPICK_IDE_IGNORE
}
#endif //NITPICK_IDE_IGNORE