//AUTOGENERATED This file has been autogenerated by bparser::details::DagPrinter::print_in_cxx
// Jan 20 2026 17:52:25

#ifndef NITPICK_IDE_IGNORE
#include "nitpick_include.hh"
using namespace bparser;
using namespace bparser::details;
#endif //NITPICK_IDE_IGNORE //This is here only to stop any IDE warnings

ExpressionDAG gen(const NodeMap& node_map){ //Do not rename this function, it is used later in the nitpick_run.cc file
	ScalarNodePtr Const_16__1 = ScalarNode::create_const(1);
	ScalarNodePtr Value_15__2 = ScalarNode::create_value(node_map.at("v1[0]"));
	ScalarNodePtr mul_14__3 = ScalarNode::create<_mul_>(Const_16__1, Value_15__2);
	ScalarNodePtr Const_13__1 = ScalarNode::create_const(2);
	ScalarNodePtr Value_12__2 = ScalarNode::create_value(node_map.at("v2[0]"));
	ScalarNodePtr mul_11__3 = ScalarNode::create<_mul_>(Const_13__1, Value_12__2);
	ScalarNodePtr add_10__4 = ScalarNode::create<_add_>(mul_14__3, mul_11__3);
	ScalarNodePtr Value_9__2 = ScalarNode::create_value(node_map.at("v1[1]"));
	ScalarNodePtr mul_8__3 = ScalarNode::create<_mul_>(Const_16__1, Value_9__2);
	ScalarNodePtr Value_7__2 = ScalarNode::create_value(node_map.at("v2[1]"));
	ScalarNodePtr mul_6__3 = ScalarNode::create<_mul_>(Const_13__1, Value_7__2);
	ScalarNodePtr add_5__4 = ScalarNode::create<_add_>(mul_8__3, mul_6__3);
	ScalarNodePtr Value_4__2 = ScalarNode::create_value(node_map.at("v1[2]"));
	ScalarNodePtr mul_3__3 = ScalarNode::create<_mul_>(Const_16__1, Value_4__2);
	ScalarNodePtr Value_2__2 = ScalarNode::create_value(node_map.at("v2[2]"));
	ScalarNodePtr mul_1__3 = ScalarNode::create<_mul_>(Const_13__1, Value_2__2);
	ScalarNodePtr add_0__4 = ScalarNode::create<_add_>(mul_3__3, mul_1__3);


	ScalarNodePtr r0 = ScalarNode::create_result(add_10__4, node_map.at("_result_[0]"));
	ScalarNodePtr r1 = ScalarNode::create_result(add_5__4, node_map.at("_result_[1]"));
	ScalarNodePtr r2 = ScalarNode::create_result(add_0__4, node_map.at("_result_[2]"));
	ExpressionDAG se({r0, r1, r2});

	return se;
} //gen
