//AUTOGENERATED This file has been autogenerated by bparser::details::DagPrinter::print_in_cxx
// Jan 20 2026 18:42:12

#ifndef NITPICK_IDE_IGNORE
#include "nitpick_include.hh"
using namespace bparser;
using namespace bparser::details;
#endif //NITPICK_IDE_IGNORE //This is here only to stop any IDE warnings
ExpressionDAG gen(const NodeMap& node_map){ //Do not rename this function, it is used later in the nitpick_run.cc file

ScalarNodePtr Value_8__2 = ScalarNode::create_value(node_map.at("v1[0]"));
ScalarNodePtr mul_7__3 = ScalarNode::create<_mul_>(Value_8__2, Value_8__2);
ScalarNodePtr Value_6__2 = ScalarNode::create_value(node_map.at("v1[1]"));
ScalarNodePtr mul_5__3 = ScalarNode::create<_mul_>(Value_6__2, Value_6__2);
ScalarNodePtr add_4__3 = ScalarNode::create<_add_>(mul_7__3, mul_5__3);
ScalarNodePtr Value_3__2 = ScalarNode::create_value(node_map.at("v1[2]"));
ScalarNodePtr mul_2__3 = ScalarNode::create<_mul_>(Value_3__2, Value_3__2);
ScalarNodePtr add_1__3 = ScalarNode::create<_add_>(add_4__3, mul_2__3);
ScalarNodePtr sqrt_0__4 = ScalarNode::create<_sqrt_>(add_1__3);


ScalarNodePtr r0 = ScalarNode::create_result(sqrt_0__4, node_map.at("_result_[]"));
ExpressionDAG se({r0});

return se;
} //gen
